### ISSUE TITLE
Align with IODE quality flag (for next release)

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-doc-transect#2]
Currently using a bespoke quality flag

**Comment by ecrockford** [comment]
Apply 9=missing to AR77 & EN706 DTN data that did not have enough for reanalysis. Could update definition of flag to include phrasing from IODE "Sample was collected, but  the observation is missing due to sample loss, contamination, etc. "

**Comment by katemorkeski** [comment]
Did not update flag definition since this is described in the methods section and to be consistent with other packages/IODE.
